config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # association
  has_many :reviews, dependent: :destroy
  # validate
  validates :name, :address, :category, presence: true
  validates :category , inclusion: ["chinese", "italian", "japanese", "french", "belgian"]
  
end

app/models/review.rb
class Review < ApplicationRecord
  # association
  belongs_to :restaurant
  # validation
  validates :content ,:rating , presence: true
  validates :rating , numericality: { only_integer: true } , :inclusion => 0..5

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_params, only: %i[show edit update destroy]



  def index
    @restaurants = Restaurant.all
  end
  def show
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurants_path
  end
  def edit
  end
  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end
  def destroy

  end
  # action top
 
  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
  def set_params
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # We need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @review.save
    redirect_to restaurants_path
  end
  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  def review_params
    params.require(:review).permit(:content,:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# bootsratp %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%#  %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%# <%= render "form", restaurant: @restaurant %>
<%= simple_form_for restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <%= f.select :category, ["chinese", "italian", "japanese", "french", "belgian"] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/_list.html.erb
<div id="restaurants">
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <% "show this restaurant", restaurant %>
  <% end %>%
</div>

app/views/restaurants/_restaurant.html.erb
<div>
   <p>
    <strong>
      Name:
      <%= restaurant.name %>
    </strong>
  </p>

  <p>
    <p>
      Address:
      <%= restaurant.address %>
    </p>
  </p>
</div>

app/views/restaurants/edit.html.erb
<%= render "form" , restaurant: @restaurant%>

app/views/restaurants/index.html.erb
<% @restaurants.map do |restaurant| %>
  <p><%= render 'restaurants/restaurant',restaurant: restaurant %></p>
  <p><%= link_to "visit this restaurant", restaurant_path(restaurant) %></p>
<% end %>
<hr>
<p><%= link_to "add a new restaurant", new_restaurant_path %></p>

app/views/restaurants/new.html.erb
<%= render "form" , restaurant: @restaurant%>

app/views/restaurants/show.html.erb
<%= render "restaurant", restaurant: @restaurant  %>


<%= link_to "Back to restaurants", restaurants_path %>
<%= link_to "Edit", edit_restaurant_path(@restaurant) %>
<%= link_to "delete", restaurants_path(@restaurant), data: { "turbo-method": :delete } %>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.text_field :content %>
  <%= f.number_field :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>